import { createSlice } from "@reduxjs/toolkit";
import { toast } from "react-toastify";

function findIndex(array, id) {
  for (let i = 0; i < array.length; i++) {
    if (array[i].id === id) return i;
  }
  return -1;
}

const initialState = {
  cart: [],
  products: [
    {
      id: 1,
      title: "Apple iPhone 15 (128 GB) - Pink",
      description:
        "Capture life's moments in style with the sleek and vibrant Apple iPhone 15 in Pink.",
      price: 899,
      discountPercentage: 17.94,
      rating: 4.44,
      stock: 3,
      brand: "Apple",
      category: "smartphones",
      thumbnail: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
      inCart: false,
      images: [
        "https://m.media-amazon.com/images/I/71v2jVh6nIL._SX522_.jpg",
        "https://m.media-amazon.com/images/I/516IO6TPGIL._SX522_.jpg",
        "https://m.media-amazon.com/images/I/712CBkmhLhL._SX522_.jpg",
        "https://m.media-amazon.com/images/I/61f4dTush1L._SX522_.jpg",
      ],
    },
    {
      id: 2,
      title: "Samsung Galaxy S24 Ultra 5G",
      description:
        "Experience the future in the palm of your hand with the Samsung Galaxy S24.",
      price: 549,
      discountPercentage: 12.96,
      rating: 4.69,
      stock: 94,
      brand: "Samsung",
      category: "smartphones",
      thumbnail: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
      inCart: false,
      images: [
        "https://m.media-amazon.com/images/I/71CXhVhpM0L._SX679_.jpg",
        "https://m.media-amazon.com/images/I/71JLhofuYJL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/71E-ptCgHcL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/71ZdFihN4YL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/71RaUP4g7KL._SX679_.jpg",
      ],
    },
    {
      id: 3,
      title:
        "Samsung Galaxy Z Fold3 5G (Phantom Silver, 12GB RAM, 256GB Storage)",
      description:
        "Unfold infinite possibilities with the Samsung Galaxy Z Fold3.",
      price: 1249,
      discountPercentage: 15.46,
      rating: 4.09,
      stock: 36,
      brand: "Samsung",
      category: "smartphones",
      thumbnail: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
      inCart: false,
      images: [
        "https://m.media-amazon.com/images/I/71UmO2UOiBL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/61eAyZCxMIL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/71+6YKpnE4L._SX679_.jpg",
        "https://m.media-amazon.com/images/I/71dL4mqSl4L._SX679_.jpg",
        "https://m.media-amazon.com/images/I/81cOgwmMsxL._SX679_.jpg",
      ],
    },
    {
      id: 4,
      title: "OnePlus 12 (Flowy Emerald, 16GB RAM, 512GB Storage)",
      description:
        "Experience the enchantment of the OnePlus 12 in Flowy Emerald.",
      price: 280,
      discountPercentage: 17.91,
      rating: 4.3,
      stock: 123,
      brand: "OnePlus",
      category: "smartphones",
      thumbnail: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
      inCart: false,
      images: [
        "https://m.media-amazon.com/images/I/61BAuSC0UnL._SX522_.jpg",
        "https://m.media-amazon.com/images/I/61CEiTA5WWL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/51ui6USIv7L._SX679_.jpg",
        "https://m.media-amazon.com/images/I/61AplC-qoML._SX679_.jpg",
        "https://m.media-amazon.com/images/I/61fVA2RaThL._SX679_.jpg",
      ],
    },
    {
      id: 5,
      title: "iQOO 12 5G (Alpha, 12GB RAM, 256GB Storage)",
      description: "Unleash the power of speed with the iQOO 12.",
      price: 499,
      discountPercentage: 10.58,
      rating: 4.09,
      stock: 32,
      brand: "Vivo",
      category: "smartphones",
      thumbnail: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
      inCart: false,
      images: [
        "https://m.media-amazon.com/images/I/61JUyx1-SbL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/71P0B0AkteL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/6196XvphsML._SX679_.jpg",
        "https://m.media-amazon.com/images/I/71Mxrqy7rEL._SX679_.jpg",
      ],
    },
    {
      id: 6,
      title: "Apple MacBook Pro (14-inch, M1 Pro Chip)",
      description:
        "Power through any task with the new Apple MacBook Pro featuring the M1 Pro chip.",
      price: 1999,
      discountPercentage: 12.43,
      rating: 4.8,
      stock: 22,
      brand: "Apple",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/6/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 7,
      title: "Samsung Galaxy Watch 5 (40mm, Bluetooth)",
      description:
        "Track your health with precision using the Samsung Galaxy Watch 5.",
      price: 279,
      discountPercentage: 9.78,
      rating: 4.6,
      stock: 50,
      brand: "Samsung",
      category: "wearables",
      thumbnail: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 8,
      title: "Bose QuietComfort 45 Bluetooth Headphones",
      description:
        "Experience unmatched sound quality and comfort with Bose QuietComfort 45.",
      price: 329,
      discountPercentage: 15.28,
      rating: 4.8,
      stock: 25,
      brand: "Bose",
      category: "earphones",
      thumbnail: "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 9,
      title: "Sony WH-1000XM4 Noise Cancelling Headphones",
      description:
        "Enjoy crystal-clear sound with Sony's industry-leading noise-canceling headphones.",
      price: 348,
      discountPercentage: 18.75,
      rating: 4.9,
      stock: 45,
      brand: "Sony",
      category: "earphones",
      thumbnail: "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 10,
      title: "Logitech G Pro Wireless Gaming Mouse",
      description:
        "Achieve precision in every movement with the Logitech G Pro Wireless Gaming Mouse.",
      price: 129,
      discountPercentage: 10.34,
      rating: 4.7,
      stock: 60,
      brand: "Logitech",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/10/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 11,
      title: "JBL Flip 5 Bluetooth Speaker",
      description:
        "Enjoy rich, high-quality sound with the compact and portable JBL Flip 5 Bluetooth speaker.",
      price: 119,
      discountPercentage: 15.46,
      rating: 4.6,
      stock: 73,
      brand: "JBL",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 12,
      title: "Microsoft Surface Laptop 4",
      description:
        "Create, work, and play with the powerful Microsoft Surface Laptop 4, featuring a sleek design.",
      price: 1499,
      discountPercentage: 10.5,
      rating: 4.7,
      stock: 30,
      brand: "Microsoft",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 13,
      title: "Apple AirPods Pro (2nd Generation)",
      description:
        "Experience the next level of sound with the Apple AirPods Pro 2nd Generation with active noise cancellation.",
      price: 249,
      discountPercentage: 12.3,
      rating: 4.8,
      stock: 60,
      brand: "Apple",
      category: "earphones",
      thumbnail: "https://i.dummyjson.com/data/products/13/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 14,
      title: "Anker PowerCore 10000 Portable Charger",
      description:
        "Charge your devices on-the-go with the compact Anker PowerCore 10000 portable charger.",
      price: 29,
      discountPercentage: 8.5,
      rating: 4.7,
      stock: 150,
      brand: "Anker",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 15,
      title: "Fitbit Charge 5 Fitness Tracker",
      description:
        "Track your health and activity with the stylish and feature-rich Fitbit Charge 5 Fitness Tracker.",
      price: 149,
      discountPercentage: 18.4,
      rating: 4.5,
      stock: 92,
      brand: "Fitbit",
      category: "wearables",
      thumbnail: "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 16,
      title: "Garmin Forerunner 945 GPS Smartwatch",
      description:
        "Stay on track with the Garmin Forerunner 945, your ultimate GPS smartwatch for fitness and outdoor adventures.",
      price: 599,
      discountPercentage: 10.2,
      rating: 4.6,
      stock: 45,
      brand: "Garmin",
      category: "wearables",
      thumbnail: "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 17,
      title: "DJI Mini 2 Drone",
      description:
        "Capture stunning aerial shots with the DJI Mini 2 drone, a compact yet powerful drone with 4K camera.",
      price: 449,
      discountPercentage: 8.1,
      rating: 4.7,
      stock: 50,
      brand: "DJI",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/17/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 18,
      title: "Razer Kraken V3 X Gaming Headset",
      description:
        "Enhance your gaming experience with the Razer Kraken V3 X, featuring immersive 7.1 surround sound.",
      price: 69,
      discountPercentage: 10.25,
      rating: 4.4,
      stock: 100,
      brand: "Razer",
      category: "earphones",
      thumbnail: "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 19,
      title: "Sony PlayStation 5 Console",
      description:
        "Experience next-gen gaming with the Sony PlayStation 5 console, featuring stunning graphics and fast load times.",
      price: 499,
      discountPercentage: 5.5,
      rating: 4.9,
      stock: 20,
      brand: "Sony",
      category: "gaming",
      thumbnail: "https://i.dummyjson.com/data/products/19/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 20,
      title: "Xbox Series X Console",
      description:
        "Level up your gaming with the Xbox Series X, designed for unparalleled performance and immersive experiences.",
      price: 499,
      discountPercentage: 4.8,
      rating: 4.8,
      stock: 33,
      brand: "Microsoft",
      category: "gaming",
      thumbnail: "https://i.dummyjson.com/data/products/20/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 21,
      title: "Bose QuietComfort 35 II Wireless Headphones",
      description:
        "Enjoy high-quality sound and noise cancellation with Bose QuietComfort 35 II Wireless Headphones.",
      price: 299,
      discountPercentage: 13.3,
      rating: 4.8,
      stock: 65,
      brand: "Bose",
      category: "earphones",
      thumbnail: "https://i.dummyjson.com/data/products/21/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 22,
      title: "Apple MacBook Air (13-inch, M2 Chip)",
      description:
        "Lightweight, fast, and powerful—Apple MacBook Air with the new M2 chip.",
      price: 1099,
      discountPercentage: 5.5,
      rating: 4.9,
      stock: 40,
      brand: "Apple",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/22/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 23,
      title: "Samsung T7 Portable SSD 1TB",
      description:
        "Fast, secure, and durable—store your data with Samsung T7 Portable SSD 1TB.",
      price: 99,
      discountPercentage: 14.8,
      rating: 4.7,
      stock: 50,
      brand: "Samsung",
      category: "storage devices",
      thumbnail: "https://i.dummyjson.com/data/products/23/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 24,
      title: "SanDisk Extreme 500GB External SSD",
      description:
        "Get fast data transfer speeds and reliability with the SanDisk Extreme 500GB External SSD.",
      price: 75,
      discountPercentage: 17.2,
      rating: 4.6,
      stock: 65,
      brand: "SanDisk",
      category: "storage devices",
      thumbnail: "https://i.dummyjson.com/data/products/24/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 25,
      title: "Apple Watch Series 7 GPS, 45mm",
      description:
        "Stay connected, track your fitness, and experience fast charging with the Apple Watch Series 7.",
      price: 399,
      discountPercentage: 10.1,
      rating: 4.8,
      stock: 80,
      brand: "Apple",
      category: "wearables",
      thumbnail: "https://i.dummyjson.com/data/products/25/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 26,
      title: "Sony WH-1000XM4 Wireless Noise Cancelling Headphones",
      description:
        "Enjoy industry-leading noise cancellation with Sony WH-1000XM4 wireless headphones.",
      price: 348,
      discountPercentage: 14.5,
      rating: 4.7,
      stock: 120,
      brand: "Sony",
      category: "earphones",
      thumbnail: "https://i.dummyjson.com/data/products/26/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 27,
      title: "Logitech G Pro X Wireless Gaming Headset",
      description:
        "Take your gaming to the next level with the Logitech G Pro X wireless headset, featuring Blue VO!CE mic technology.",
      price: 199,
      discountPercentage: 12.3,
      rating: 4.5,
      stock: 45,
      brand: "Logitech",
      category: "earphones",
      thumbnail: "https://i.dummyjson.com/data/products/27/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 28,
      title: "Kindle Paperwhite 10th Generation",
      description:
        "Read books with ease on the Amazon Kindle Paperwhite 10th generation with built-in light.",
      price: 129,
      discountPercentage: 8.9,
      rating: 4.7,
      stock: 200,
      brand: "Amazon",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/28/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 29,
      title: "Samsung Galaxy Tab S7 Wi-Fi",
      description:
        "Experience seamless multitasking with the Samsung Galaxy Tab S7, a tablet with ultra-smooth performance.",
      price: 649,
      discountPercentage: 5.0,
      rating: 4.6,
      stock: 60,
      brand: "Samsung",
      category: "tablets",
      thumbnail: "https://i.dummyjson.com/data/products/29/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 30,
      title: "Google Pixel 6 (128GB)",
      description:
        "Capture your moments in stunning detail with the Google Pixel 6, powered by Google Tensor.",
      price: 649,
      discountPercentage: 10.3,
      rating: 4.5,
      stock: 85,
      brand: "Google",
      category: "smartphones",
      thumbnail: "https://i.dummyjson.com/data/products/30/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 31,
      title: "Apple AirPods Pro (2nd generation)",
      description:
        "Enjoy high-fidelity sound and advanced noise cancellation with Apple AirPods Pro (2nd generation).",
      price: 249,
      discountPercentage: 10.2,
      rating: 4.8,
      stock: 100,
      brand: "Apple",
      category: "earphones",
      thumbnail: "https://i.dummyjson.com/data/products/31/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 32,
      title: "Microsoft Surface Pro 7 (12.3-inch)",
      description:
        "Portable, powerful, and versatile: the Microsoft Surface Pro 7 is a perfect 2-in-1 device for work and play.",
      price: 749,
      discountPercentage: 12.0,
      rating: 4.6,
      stock: 50,
      brand: "Microsoft",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/32/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 33,
      title: "Logitech MX Master 3S Wireless Mouse",
      description:
        "A master in comfort, precision, and power: The Logitech MX Master 3S Wireless Mouse.",
      price: 99,
      discountPercentage: 15.0,
      rating: 4.7,
      stock: 120,
      brand: "Logitech",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/33/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 34,
      title: "Anker PowerCore 10000 Portable Charger",
      description:
        "Charge your devices anytime, anywhere with the Anker PowerCore 10000 Portable Charger.",
      price: 29.99,
      discountPercentage: 20.5,
      rating: 4.6,
      stock: 200,
      brand: "Anker",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/34/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 35,
      title: "Seagate Backup Plus 1TB External Hard Drive",
      description:
        "Backup your important files with Seagate Backup Plus 1TB External Hard Drive.",
      price: 55,
      discountPercentage: 16.5,
      rating: 4.5,
      stock: 150,
      brand: "Seagate",
      category: "storage devices",
      thumbnail: "https://i.dummyjson.com/data/products/35/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 36,
      title: "HP 15 Laptop (15.6-inch, i5, 8GB RAM, 512GB SSD)",
      description:
        "An ideal laptop for everyday tasks, the HP 15 offers solid performance in a slim design.",
      price: 649,
      discountPercentage: 7.8,
      rating: 4.4,
      stock: 100,
      brand: "HP",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/36/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 37,
      title: "Epson EcoTank ET-2720 Wireless Printer",
      description:
        "Save money on ink and print with ease with Epson EcoTank ET-2720 Wireless Printer.",
      price: 199,
      discountPercentage: 10.0,
      rating: 4.4,
      stock: 70,
      brand: "Epson",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/37/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 38,
      title: "Fujifilm Instax Mini 11 Instant Camera Bundle",
      description:
        "Capture moments instantly with the Fujifilm Instax Mini 11 Instant Camera.",
      price: 69.99,
      discountPercentage: 13.5,
      rating: 4.7,
      stock: 50,
      brand: "Fujifilm",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/38/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 39,
      title: "GoPro HERO9 Black 5K Action Camera",
      description:
        "Capture stunning 5K video and sharp photos with the GoPro HERO9 Black action camera.",
      price: 399,
      discountPercentage: 15.0,
      rating: 4.8,
      stock: 60,
      brand: "GoPro",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/39/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 40,
      title: "JBL Flip 5 Waterproof Bluetooth Speaker",
      description:
        "Play your favorite tunes with the JBL Flip 5 waterproof Bluetooth speaker, with powerful sound and deep bass.",
      price: 119,
      discountPercentage: 10.5,
      rating: 4.7,
      stock: 120,
      brand: "JBL",
      category: "audio",
      thumbnail: "https://i.dummyjson.com/data/products/40/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 41,
      title: "Sony WH-1000XM4 Wireless Noise Cancelling Headphones",
      description:
        "Experience immersive sound with Sony WH-1000XM4 wireless headphones with active noise cancelling.",
      price: 348,
      discountPercentage: 13.5,
      rating: 4.9,
      stock: 80,
      brand: "Sony",
      category: "audio",
      thumbnail: "https://i.dummyjson.com/data/products/41/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 42,
      title: "Bose QuietComfort 45 Bluetooth Headphones",
      description:
        "The Bose QuietComfort 45 headphones offer a rich audio experience with top-tier noise cancellation.",
      price: 329,
      discountPercentage: 9.8,
      rating: 4.7,
      stock: 75,
      brand: "Bose",
      category: "audio",
      thumbnail: "https://i.dummyjson.com/data/products/42/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 43,
      title: "Canon EOS Rebel T7 DSLR Camera Bundle",
      description:
        "Get everything you need to start photography with the Canon EOS Rebel T7 DSLR camera bundle.",
      price: 599,
      discountPercentage: 14.0,
      rating: 4.6,
      stock: 50,
      brand: "Canon",
      category: "cameras",
      thumbnail: "https://i.dummyjson.com/data/products/43/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 44,
      title: "Nikon D3500 DSLR Camera with 18-55mm Lens",
      description:
        "The Nikon D3500 DSLR camera offers amazing image quality and portability.",
      price: 499,
      discountPercentage: 10.0,
      rating: 4.5,
      stock: 40,
      brand: "Nikon",
      category: "cameras",
      thumbnail: "https://i.dummyjson.com/data/products/44/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 45,
      title: "Bose SoundLink Revolve+ Bluetooth Speaker",
      description:
        "A portable speaker with deep bass and 360-degree sound, perfect for indoor and outdoor use.",
      price: 299,
      discountPercentage: 8.5,
      rating: 4.7,
      stock: 65,
      brand: "Bose",
      category: "audio",
      thumbnail: "https://i.dummyjson.com/data/products/45/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 46,
      title: "Fitbit Charge 5 Fitness Tracker",
      description:
        "Track your fitness with the advanced Fitbit Charge 5 tracker with built-in GPS and heart rate monitoring.",
      price: 179,
      discountPercentage: 12.0,
      rating: 4.6,
      stock: 150,
      brand: "Fitbit",
      category: "fitness",
      thumbnail: "https://i.dummyjson.com/data/products/46/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 47,
      title: "Garmin Forerunner 245 Music GPS Running Watch",
      description:
        "Enhance your workouts with the Garmin Forerunner 245 Music GPS running watch with built-in music storage.",
      price: 299,
      discountPercentage: 10.5,
      rating: 4.7,
      stock: 70,
      brand: "Garmin",
      category: "fitness",
      thumbnail: "https://i.dummyjson.com/data/products/47/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 48,
      title: "Apple Watch Series 7 GPS, 41mm",
      description:
        "The Apple Watch Series 7 offers fitness tracking, health insights, and stunning display.",
      price: 399,
      discountPercentage: 9.0,
      rating: 4.8,
      stock: 100,
      brand: "Apple",
      category: "wearables",
      thumbnail: "https://i.dummyjson.com/data/products/48/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 49,
      title: "Samsung Galaxy Watch 4 Classic",
      description:
        "The Samsung Galaxy Watch 4 Classic is a premium smartwatch with fitness tracking and advanced health monitoring.",
      price: 249,
      discountPercentage: 11.2,
      rating: 4.6,
      stock: 80,
      brand: "Samsung",
      category: "wearables",
      thumbnail: "https://i.dummyjson.com/data/products/49/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 50,
      title: "Fitbit Sense Advanced Smartwatch",
      description:
        "Stay on top of your health and fitness with the Fitbit Sense smartwatch, featuring ECG and skin temperature sensors.",
      price: 299,
      discountPercentage: 8.0,
      rating: 4.7,
      stock: 120,
      brand: "Fitbit",
      category: "wearables",
      thumbnail: "https://i.dummyjson.com/data/products/50/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 51,
      title: "Sony PlayStation 5 Console",
      description:
        "The Sony PlayStation 5 is the next-generation gaming console with ultra-fast SSD, Ray Tracing, and an incredible selection of games.",
      price: 499,
      discountPercentage: 5.0,
      rating: 4.9,
      stock: 200,
      brand: "Sony",
      category: "gaming",
      thumbnail: "https://i.dummyjson.com/data/products/51/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 52,
      title: "Microsoft Xbox Series X",
      description:
        "Power your gaming experience with the Xbox Series X, the most powerful gaming console.",
      price: 499,
      discountPercentage: 6.0,
      rating: 4.8,
      stock: 150,
      brand: "Microsoft",
      category: "gaming",
      thumbnail: "https://i.dummyjson.com/data/products/52/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 53,
      title: "Nintendo Switch OLED Model",
      description:
        "Enjoy the immersive world of gaming with the Nintendo Switch OLED, offering vibrant visuals and portable gameplay.",
      price: 349,
      discountPercentage: 10.0,
      rating: 4.7,
      stock: 200,
      brand: "Nintendo",
      category: "gaming",
      thumbnail: "https://i.dummyjson.com/data/products/53/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 54,
      title: "Samsung 65-inch 4K UHD Smart TV",
      description:
        "Enjoy stunning visuals and an immersive entertainment experience with the Samsung 65-inch 4K UHD Smart TV.",
      price: 799,
      discountPercentage: 7.0,
      rating: 4.5,
      stock: 100,
      brand: "Samsung",
      category: "electronics",
      thumbnail: "https://i.dummyjson.com/data/products/54/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 55,
      title: "LG 55-inch OLED 4K TV",
      description:
        "An OLED masterpiece, the LG 55-inch 4K TV brings your favorite movies and shows to life with true-to-life color and clarity.",
      price: 1499,
      discountPercentage: 15.0,
      rating: 4.8,
      stock: 60,
      brand: "LG",
      category: "electronics",
      thumbnail: "https://i.dummyjson.com/data/products/55/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 56,
      title: "Apple MacBook Pro 13-inch M1 Chip",
      description:
        "The Apple MacBook Pro with M1 chip is the ultimate power machine with enhanced performance, ideal for professionals.",
      price: 1299,
      discountPercentage: 10.0,
      rating: 4.9,
      stock: 40,
      brand: "Apple",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/56/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 57,
      title: "Dell XPS 13 Laptop",
      description:
        "The Dell XPS 13 offers ultrathin design, amazing performance, and an ultra-responsive 13-inch display.",
      price: 999,
      discountPercentage: 5.0,
      rating: 4.7,
      stock: 80,
      brand: "Dell",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/57/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 58,
      title: "HP Spectre x360 Laptop",
      description:
        "The HP Spectre x360 is a sleek and versatile 2-in-1 laptop with incredible power and a high-resolution touchscreen display.",
      price: 1299,
      discountPercentage: 7.0,
      rating: 4.6,
      stock: 60,
      brand: "HP",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/58/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 59,
      title: "Lenovo ThinkPad X1 Carbon Gen 9",
      description:
        "Lenovo ThinkPad X1 Carbon is a powerful business laptop with a stunning 14-inch display and long battery life.",
      price: 1599,
      discountPercentage: 10.0,
      rating: 4.8,
      stock: 30,
      brand: "Lenovo",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/59/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 60,
      title: "Acer Predator Helios 300 Gaming Laptop",
      description:
        "The Acer Predator Helios 300 features a powerful i7 processor, an NVIDIA RTX 3060 GPU, and a 144Hz display for an immersive gaming experience.",
      price: 1299,
      discountPercentage: 12.0,
      rating: 4.6,
      stock: 90,
      brand: "Acer",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/60/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 61,
      title: "Bose QuietComfort 35 II Wireless Bluetooth Headphones",
      description:
        "The Bose QuietComfort 35 II headphones offer superior noise-canceling technology, incredible sound quality, and comfortable fit.",
      price: 299,
      discountPercentage: 10.0,
      rating: 4.7,
      stock: 150,
      brand: "Bose",
      category: "headphones",
      thumbnail: "https://i.dummyjson.com/data/products/61/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 62,
      title: "Sony WH-1000XM4 Noise Cancelling Wireless Headphones",
      description:
        "Enjoy exceptional sound quality and industry-leading noise cancellation with the Sony WH-1000XM4 headphones.",
      price: 349,
      discountPercentage: 8.0,
      rating: 4.9,
      stock: 200,
      brand: "Sony",
      category: "headphones",
      thumbnail: "https://i.dummyjson.com/data/products/62/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 63,
      title: "Beats Studio3 Wireless Noise Cancelling Over-Ear Headphones",
      description:
        "Beats Studio3 headphones deliver high-quality sound and superior noise cancellation for the best listening experience.",
      price: 379,
      discountPercentage: 12.0,
      rating: 4.8,
      stock: 120,
      brand: "Beats",
      category: "headphones",
      thumbnail: "https://i.dummyjson.com/data/products/63/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 64,
      title: "Apple AirPods Pro (2nd Generation)",
      description:
        "The Apple AirPods Pro delivers high-fidelity audio, adaptive transparency, and active noise cancellation in a small, portable design.",
      price: 249,
      discountPercentage: 5.0,
      rating: 4.9,
      stock: 300,
      brand: "Apple",
      category: "headphones",
      thumbnail: "https://i.dummyjson.com/data/products/64/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 65,
      title: "Samsung T7 Portable SSD 1TB",
      description:
        "The Samsung T7 Portable SSD offers fast transfer speeds with the convenience of compact portability, perfect for backup and storage needs.",
      price: 119,
      discountPercentage: 15.0,
      rating: 4.7,
      stock: 200,
      brand: "Samsung",
      category: "storage",
      thumbnail: "https://i.dummyjson.com/data/products/65/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 66,
      title: "SanDisk Ultra 1TB USB 3.0 Flash Drive",
      description:
        "The SanDisk Ultra 1TB USB Flash Drive offers fast data transfer with a compact and durable design for storing documents, photos, and videos.",
      price: 54,
      discountPercentage: 20.0,
      rating: 4.6,
      stock: 300,
      brand: "SanDisk",
      category: "storage",
      thumbnail: "https://i.dummyjson.com/data/products/66/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 67,
      title: "Western Digital 2TB My Passport Portable Hard Drive",
      description:
        "The WD My Passport 2TB portable hard drive is a high-capacity external storage solution with fast read/write speeds and sleek design.",
      price: 89,
      discountPercentage: 10.0,
      rating: 4.8,
      stock: 250,
      brand: "Western Digital",
      category: "storage",
      thumbnail: "https://i.dummyjson.com/data/products/67/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 68,
      title: "Seagate Expansion 4TB Portable External Hard Drive",
      description:
        "The Seagate Expansion 4TB portable external hard drive offers large storage capacity and fast data transfer for all your files and media.",
      price: 105,
      discountPercentage: 15.0,
      rating: 4.7,
      stock: 180,
      brand: "Seagate",
      category: "storage",
      thumbnail: "https://i.dummyjson.com/data/products/68/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 69,
      title: "Kingston A2000 1TB NVMe Internal SSD",
      description:
        "Boost your computer's performance with the Kingston A2000 1TB NVMe SSD, delivering ultra-fast read and write speeds for a smooth experience.",
      price: 69,
      discountPercentage: 12.0,
      rating: 4.6,
      stock: 160,
      brand: "Kingston",
      category: "storage",
      thumbnail: "https://i.dummyjson.com/data/products/69/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 70,
      title: "HyperX Alloy FPS Pro Mechanical Gaming Keyboard",
      description:
        "The HyperX Alloy FPS Pro is a compact mechanical keyboard designed for FPS gamers, featuring red LED backlighting and responsive keys.",
      price: 69,
      discountPercentage: 15.0,
      rating: 4.7,
      stock: 110,
      brand: "HyperX",
      category: "gaming",
      thumbnail: "https://i.dummyjson.com/data/products/70/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 71,
      title: "Razer DeathAdder V2 Wired Gaming Mouse",
      description:
        "The Razer DeathAdder V2 is a highly precise wired gaming mouse, designed for comfort and performance with optical mouse switches.",
      price: 49,
      discountPercentage: 10.0,
      rating: 4.8,
      stock: 150,
      brand: "Razer",
      category: "gaming",
      thumbnail: "https://i.dummyjson.com/data/products/71/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 72,
      title: "Logitech G Pro X Superlight Wireless Gaming Mouse",
      description:
        "The Logitech G Pro X Superlight is an ultra-lightweight wireless gaming mouse, built for professional-grade precision and performance.",
      price: 149,
      discountPercentage: 5.0,
      rating: 4.9,
      stock: 130,
      brand: "Logitech",
      category: "gaming",
      thumbnail: "https://i.dummyjson.com/data/products/72/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 73,
      title: "Corsair K70 RGB MK.2 Mechanical Gaming Keyboard",
      description:
        "The Corsair K70 RGB MK.2 is a premium mechanical gaming keyboard with Cherry MX key switches and customizable RGB backlighting.",
      price: 159,
      discountPercentage: 12.0,
      rating: 4.7,
      stock: 110,
      brand: "Corsair",
      category: "gaming",
      thumbnail: "https://i.dummyjson.com/data/products/73/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 74,
      title: "Acer Predator Helios 300 Gaming Laptop",
      description:
        "The Acer Predator Helios 300 features a 15.6-inch Full HD display, Intel i7 processor, and NVIDIA GTX 1660 Ti graphics, perfect for gaming.",
      price: 1299,
      discountPercentage: 10.0,
      rating: 4.6,
      stock: 70,
      brand: "Acer",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/74/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 75,
      title: "Asus ROG Zephyrus G14 Gaming Laptop",
      description:
        "The Asus ROG Zephyrus G14 offers incredible gaming performance with an AMD Ryzen 9 processor, NVIDIA GeForce RTX 3070, and a 14-inch display.",
      price: 1799,
      discountPercentage: 7.0,
      rating: 4.8,
      stock: 60,
      brand: "Asus",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/75/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 76,
      title: "Dell XPS 15 9500 Laptop",
      description:
        "The Dell XPS 15 is a powerful laptop with a 15.6-inch 4K OLED display, Intel Core i9 processor, and NVIDIA GTX 1650 Ti graphics.",
      price: 2399,
      discountPercentage: 15.0,
      rating: 4.9,
      stock: 45,
      brand: "Dell",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/76/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 77,
      title: "HP Spectre x360 13.3-Inch Laptop",
      description:
        "The HP Spectre x360 features a 13.3-inch touchscreen, Intel i7 processor, and 512GB SSD for all your productivity and creative needs.",
      price: 1499,
      discountPercentage: 10.0,
      rating: 4.7,
      stock: 80,
      brand: "HP",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/77/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 78,
      title: "Apple MacBook Air with M1 Chip",
      description:
        "The Apple MacBook Air with M1 chip is thin, lightweight, and packed with performance. Featuring 13.3-inch Retina display and long battery life.",
      price: 999,
      discountPercentage: 5.0,
      rating: 4.8,
      stock: 120,
      brand: "Apple",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/78/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 79,
      title: "Microsoft Surface Laptop 4",
      description:
        "The Microsoft Surface Laptop 4 is sleek and powerful, with a 13.5-inch PixelSense display, Intel Core i7 processor, and long battery life.",
      price: 1299,
      discountPercentage: 8.0,
      rating: 4.7,
      stock: 150,
      brand: "Microsoft",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/79/thumbnail.jpg",
      inCart: false,
      images: [],
    },
  ],
  filteredProducts: [
    {
      id: 1,
      title: "Apple iPhone 15 (128 GB) - Pink",
      description:
        "Capture life's moments in style with the sleek and vibrant Apple iPhone 15 in Pink.",
      price: 899,
      discountPercentage: 17.94,
      rating: 4.44,
      stock: 3,
      brand: "Apple",
      category: "smartphones",
      thumbnail: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
      inCart: false,
      images: [
        "https://m.media-amazon.com/images/I/71v2jVh6nIL._SX522_.jpg",
        "https://m.media-amazon.com/images/I/516IO6TPGIL._SX522_.jpg",
        "https://m.media-amazon.com/images/I/712CBkmhLhL._SX522_.jpg",
        "https://m.media-amazon.com/images/I/61f4dTush1L._SX522_.jpg",
      ],
    },
    {
      id: 2,
      title: "Samsung Galaxy S24 Ultra 5G",
      description:
        "Experience the future in the palm of your hand with the Samsung Galaxy S24.",
      price: 549,
      discountPercentage: 12.96,
      rating: 4.69,
      stock: 94,
      brand: "Samsung",
      category: "smartphones",
      thumbnail: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
      inCart: false,
      images: [
        "https://m.media-amazon.com/images/I/71CXhVhpM0L._SX679_.jpg",
        "https://m.media-amazon.com/images/I/71JLhofuYJL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/71E-ptCgHcL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/71ZdFihN4YL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/71RaUP4g7KL._SX679_.jpg",
      ],
    },
    {
      id: 3,
      title:
        "Samsung Galaxy Z Fold3 5G (Phantom Silver, 12GB RAM, 256GB Storage)",
      description:
        "Unfold infinite possibilities with the Samsung Galaxy Z Fold3.",
      price: 1249,
      discountPercentage: 15.46,
      rating: 4.09,
      stock: 36,
      brand: "Samsung",
      category: "smartphones",
      thumbnail: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
      inCart: false,
      images: [
        "https://m.media-amazon.com/images/I/71UmO2UOiBL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/61eAyZCxMIL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/71+6YKpnE4L._SX679_.jpg",
        "https://m.media-amazon.com/images/I/71dL4mqSl4L._SX679_.jpg",
        "https://m.media-amazon.com/images/I/81cOgwmMsxL._SX679_.jpg",
      ],
    },
    {
      id: 4,
      title: "OnePlus 12 (Flowy Emerald, 16GB RAM, 512GB Storage)",
      description:
        "Experience the enchantment of the OnePlus 12 in Flowy Emerald.",
      price: 280,
      discountPercentage: 17.91,
      rating: 4.3,
      stock: 123,
      brand: "OnePlus",
      category: "smartphones",
      thumbnail: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
      inCart: false,
      images: [
        "https://m.media-amazon.com/images/I/61BAuSC0UnL._SX522_.jpg",
        "https://m.media-amazon.com/images/I/61CEiTA5WWL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/51ui6USIv7L._SX679_.jpg",
        "https://m.media-amazon.com/images/I/61AplC-qoML._SX679_.jpg",
        "https://m.media-amazon.com/images/I/61fVA2RaThL._SX679_.jpg",
      ],
    },
    {
      id: 5,
      title: "iQOO 12 5G (Alpha, 12GB RAM, 256GB Storage)",
      description: "Unleash the power of speed with the iQOO 12.",
      price: 499,
      discountPercentage: 10.58,
      rating: 4.09,
      stock: 32,
      brand: "Vivo",
      category: "smartphones",
      thumbnail: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
      inCart: false,
      images: [
        "https://m.media-amazon.com/images/I/61JUyx1-SbL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/71P0B0AkteL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/6196XvphsML._SX679_.jpg",
        "https://m.media-amazon.com/images/I/71Mxrqy7rEL._SX679_.jpg",
      ],
    },
    {
      id: 6,
      title: "Apple MacBook Pro (14-inch, M1 Pro Chip)",
      description:
        "Power through any task with the new Apple MacBook Pro featuring the M1 Pro chip.",
      price: 1999,
      discountPercentage: 12.43,
      rating: 4.8,
      stock: 22,
      brand: "Apple",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/6/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 7,
      title: "Samsung Galaxy Watch 5 (40mm, Bluetooth)",
      description:
        "Track your health with precision using the Samsung Galaxy Watch 5.",
      price: 279,
      discountPercentage: 9.78,
      rating: 4.6,
      stock: 50,
      brand: "Samsung",
      category: "wearables",
      thumbnail: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 8,
      title: "Bose QuietComfort 45 Bluetooth Headphones",
      description:
        "Experience unmatched sound quality and comfort with Bose QuietComfort 45.",
      price: 329,
      discountPercentage: 15.28,
      rating: 4.8,
      stock: 25,
      brand: "Bose",
      category: "earphones",
      thumbnail: "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 9,
      title: "Sony WH-1000XM4 Noise Cancelling Headphones",
      description:
        "Enjoy crystal-clear sound with Sony's industry-leading noise-canceling headphones.",
      price: 348,
      discountPercentage: 18.75,
      rating: 4.9,
      stock: 45,
      brand: "Sony",
      category: "earphones",
      thumbnail: "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 10,
      title: "Logitech G Pro Wireless Gaming Mouse",
      description:
        "Achieve precision in every movement with the Logitech G Pro Wireless Gaming Mouse.",
      price: 129,
      discountPercentage: 10.34,
      rating: 4.7,
      stock: 60,
      brand: "Logitech",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/10/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 11,
      title: "JBL Flip 5 Bluetooth Speaker",
      description:
        "Enjoy rich, high-quality sound with the compact and portable JBL Flip 5 Bluetooth speaker.",
      price: 119,
      discountPercentage: 15.46,
      rating: 4.6,
      stock: 73,
      brand: "JBL",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 12,
      title: "Microsoft Surface Laptop 4",
      description:
        "Create, work, and play with the powerful Microsoft Surface Laptop 4, featuring a sleek design.",
      price: 1499,
      discountPercentage: 10.5,
      rating: 4.7,
      stock: 30,
      brand: "Microsoft",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 13,
      title: "Apple AirPods Pro (2nd Generation)",
      description:
        "Experience the next level of sound with the Apple AirPods Pro 2nd Generation with active noise cancellation.",
      price: 249,
      discountPercentage: 12.3,
      rating: 4.8,
      stock: 60,
      brand: "Apple",
      category: "earphones",
      thumbnail: "https://i.dummyjson.com/data/products/13/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 14,
      title: "Anker PowerCore 10000 Portable Charger",
      description:
        "Charge your devices on-the-go with the compact Anker PowerCore 10000 portable charger.",
      price: 29,
      discountPercentage: 8.5,
      rating: 4.7,
      stock: 150,
      brand: "Anker",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 15,
      title: "Fitbit Charge 5 Fitness Tracker",
      description:
        "Track your health and activity with the stylish and feature-rich Fitbit Charge 5 Fitness Tracker.",
      price: 149,
      discountPercentage: 18.4,
      rating: 4.5,
      stock: 92,
      brand: "Fitbit",
      category: "wearables",
      thumbnail: "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 16,
      title: "Garmin Forerunner 945 GPS Smartwatch",
      description:
        "Stay on track with the Garmin Forerunner 945, your ultimate GPS smartwatch for fitness and outdoor adventures.",
      price: 599,
      discountPercentage: 10.2,
      rating: 4.6,
      stock: 45,
      brand: "Garmin",
      category: "wearables",
      thumbnail: "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 17,
      title: "DJI Mini 2 Drone",
      description:
        "Capture stunning aerial shots with the DJI Mini 2 drone, a compact yet powerful drone with 4K camera.",
      price: 449,
      discountPercentage: 8.1,
      rating: 4.7,
      stock: 50,
      brand: "DJI",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/17/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 18,
      title: "Razer Kraken V3 X Gaming Headset",
      description:
        "Enhance your gaming experience with the Razer Kraken V3 X, featuring immersive 7.1 surround sound.",
      price: 69,
      discountPercentage: 10.25,
      rating: 4.4,
      stock: 100,
      brand: "Razer",
      category: "earphones",
      thumbnail: "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 19,
      title: "Sony PlayStation 5 Console",
      description:
        "Experience next-gen gaming with the Sony PlayStation 5 console, featuring stunning graphics and fast load times.",
      price: 499,
      discountPercentage: 5.5,
      rating: 4.9,
      stock: 20,
      brand: "Sony",
      category: "gaming",
      thumbnail: "https://i.dummyjson.com/data/products/19/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 20,
      title: "Xbox Series X Console",
      description:
        "Level up your gaming with the Xbox Series X, designed for unparalleled performance and immersive experiences.",
      price: 499,
      discountPercentage: 4.8,
      rating: 4.8,
      stock: 33,
      brand: "Microsoft",
      category: "gaming",
      thumbnail: "https://i.dummyjson.com/data/products/20/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 21,
      title: "Bose QuietComfort 35 II Wireless Headphones",
      description:
        "Enjoy high-quality sound and noise cancellation with Bose QuietComfort 35 II Wireless Headphones.",
      price: 299,
      discountPercentage: 13.3,
      rating: 4.8,
      stock: 65,
      brand: "Bose",
      category: "earphones",
      thumbnail: "https://i.dummyjson.com/data/products/21/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 22,
      title: "Apple MacBook Air (13-inch, M2 Chip)",
      description:
        "Lightweight, fast, and powerful—Apple MacBook Air with the new M2 chip.",
      price: 1099,
      discountPercentage: 5.5,
      rating: 4.9,
      stock: 40,
      brand: "Apple",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/22/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 23,
      title: "Samsung T7 Portable SSD 1TB",
      description:
        "Fast, secure, and durable—store your data with Samsung T7 Portable SSD 1TB.",
      price: 99,
      discountPercentage: 14.8,
      rating: 4.7,
      stock: 50,
      brand: "Samsung",
      category: "storage devices",
      thumbnail: "https://i.dummyjson.com/data/products/23/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 24,
      title: "SanDisk Extreme 500GB External SSD",
      description:
        "Get fast data transfer speeds and reliability with the SanDisk Extreme 500GB External SSD.",
      price: 75,
      discountPercentage: 17.2,
      rating: 4.6,
      stock: 65,
      brand: "SanDisk",
      category: "storage devices",
      thumbnail: "https://i.dummyjson.com/data/products/24/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 25,
      title: "Apple Watch Series 7 GPS, 45mm",
      description:
        "Stay connected, track your fitness, and experience fast charging with the Apple Watch Series 7.",
      price: 399,
      discountPercentage: 10.1,
      rating: 4.8,
      stock: 80,
      brand: "Apple",
      category: "wearables",
      thumbnail: "https://i.dummyjson.com/data/products/25/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 26,
      title: "Sony WH-1000XM4 Wireless Noise Cancelling Headphones",
      description:
        "Enjoy industry-leading noise cancellation with Sony WH-1000XM4 wireless headphones.",
      price: 348,
      discountPercentage: 14.5,
      rating: 4.7,
      stock: 120,
      brand: "Sony",
      category: "earphones",
      thumbnail: "https://i.dummyjson.com/data/products/26/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 27,
      title: "Logitech G Pro X Wireless Gaming Headset",
      description:
        "Take your gaming to the next level with the Logitech G Pro X wireless headset, featuring Blue VO!CE mic technology.",
      price: 199,
      discountPercentage: 12.3,
      rating: 4.5,
      stock: 45,
      brand: "Logitech",
      category: "earphones",
      thumbnail: "https://i.dummyjson.com/data/products/27/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 28,
      title: "Kindle Paperwhite 10th Generation",
      description:
        "Read books with ease on the Amazon Kindle Paperwhite 10th generation with built-in light.",
      price: 129,
      discountPercentage: 8.9,
      rating: 4.7,
      stock: 200,
      brand: "Amazon",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/28/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 29,
      title: "Samsung Galaxy Tab S7 Wi-Fi",
      description:
        "Experience seamless multitasking with the Samsung Galaxy Tab S7, a tablet with ultra-smooth performance.",
      price: 649,
      discountPercentage: 5.0,
      rating: 4.6,
      stock: 60,
      brand: "Samsung",
      category: "tablets",
      thumbnail: "https://i.dummyjson.com/data/products/29/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 30,
      title: "Google Pixel 6 (128GB)",
      description:
        "Capture your moments in stunning detail with the Google Pixel 6, powered by Google Tensor.",
      price: 649,
      discountPercentage: 10.3,
      rating: 4.5,
      stock: 85,
      brand: "Google",
      category: "smartphones",
      thumbnail: "https://i.dummyjson.com/data/products/30/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 31,
      title: "Apple AirPods Pro (2nd generation)",
      description:
        "Enjoy high-fidelity sound and advanced noise cancellation with Apple AirPods Pro (2nd generation).",
      price: 249,
      discountPercentage: 10.2,
      rating: 4.8,
      stock: 100,
      brand: "Apple",
      category: "earphones",
      thumbnail: "https://i.dummyjson.com/data/products/31/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 32,
      title: "Microsoft Surface Pro 7 (12.3-inch)",
      description:
        "Portable, powerful, and versatile: the Microsoft Surface Pro 7 is a perfect 2-in-1 device for work and play.",
      price: 749,
      discountPercentage: 12.0,
      rating: 4.6,
      stock: 50,
      brand: "Microsoft",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/32/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 33,
      title: "Logitech MX Master 3S Wireless Mouse",
      description:
        "A master in comfort, precision, and power: The Logitech MX Master 3S Wireless Mouse.",
      price: 99,
      discountPercentage: 15.0,
      rating: 4.7,
      stock: 120,
      brand: "Logitech",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/33/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 34,
      title: "Anker PowerCore 10000 Portable Charger",
      description:
        "Charge your devices anytime, anywhere with the Anker PowerCore 10000 Portable Charger.",
      price: 29.99,
      discountPercentage: 20.5,
      rating: 4.6,
      stock: 200,
      brand: "Anker",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/34/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 35,
      title: "Seagate Backup Plus 1TB External Hard Drive",
      description:
        "Backup your important files with Seagate Backup Plus 1TB External Hard Drive.",
      price: 55,
      discountPercentage: 16.5,
      rating: 4.5,
      stock: 150,
      brand: "Seagate",
      category: "storage devices",
      thumbnail: "https://i.dummyjson.com/data/products/35/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 36,
      title: "HP 15 Laptop (15.6-inch, i5, 8GB RAM, 512GB SSD)",
      description:
        "An ideal laptop for everyday tasks, the HP 15 offers solid performance in a slim design.",
      price: 649,
      discountPercentage: 7.8,
      rating: 4.4,
      stock: 100,
      brand: "HP",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/36/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 37,
      title: "Epson EcoTank ET-2720 Wireless Printer",
      description:
        "Save money on ink and print with ease with Epson EcoTank ET-2720 Wireless Printer.",
      price: 199,
      discountPercentage: 10.0,
      rating: 4.4,
      stock: 70,
      brand: "Epson",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/37/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 38,
      title: "Fujifilm Instax Mini 11 Instant Camera Bundle",
      description:
        "Capture moments instantly with the Fujifilm Instax Mini 11 Instant Camera.",
      price: 69.99,
      discountPercentage: 13.5,
      rating: 4.7,
      stock: 50,
      brand: "Fujifilm",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/38/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 39,
      title: "GoPro HERO9 Black 5K Action Camera",
      description:
        "Capture stunning 5K video and sharp photos with the GoPro HERO9 Black action camera.",
      price: 399,
      discountPercentage: 15.0,
      rating: 4.8,
      stock: 60,
      brand: "GoPro",
      category: "accessories",
      thumbnail: "https://i.dummyjson.com/data/products/39/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 40,
      title: "JBL Flip 5 Waterproof Bluetooth Speaker",
      description:
        "Play your favorite tunes with the JBL Flip 5 waterproof Bluetooth speaker, with powerful sound and deep bass.",
      price: 119,
      discountPercentage: 10.5,
      rating: 4.7,
      stock: 120,
      brand: "JBL",
      category: "audio",
      thumbnail: "https://i.dummyjson.com/data/products/40/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 41,
      title: "Sony WH-1000XM4 Wireless Noise Cancelling Headphones",
      description:
        "Experience immersive sound with Sony WH-1000XM4 wireless headphones with active noise cancelling.",
      price: 348,
      discountPercentage: 13.5,
      rating: 4.9,
      stock: 80,
      brand: "Sony",
      category: "audio",
      thumbnail: "https://i.dummyjson.com/data/products/41/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 42,
      title: "Bose QuietComfort 45 Bluetooth Headphones",
      description:
        "The Bose QuietComfort 45 headphones offer a rich audio experience with top-tier noise cancellation.",
      price: 329,
      discountPercentage: 9.8,
      rating: 4.7,
      stock: 75,
      brand: "Bose",
      category: "audio",
      thumbnail: "https://i.dummyjson.com/data/products/42/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 43,
      title: "Canon EOS Rebel T7 DSLR Camera Bundle",
      description:
        "Get everything you need to start photography with the Canon EOS Rebel T7 DSLR camera bundle.",
      price: 599,
      discountPercentage: 14.0,
      rating: 4.6,
      stock: 50,
      brand: "Canon",
      category: "cameras",
      thumbnail: "https://i.dummyjson.com/data/products/43/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 44,
      title: "Nikon D3500 DSLR Camera with 18-55mm Lens",
      description:
        "The Nikon D3500 DSLR camera offers amazing image quality and portability.",
      price: 499,
      discountPercentage: 10.0,
      rating: 4.5,
      stock: 40,
      brand: "Nikon",
      category: "cameras",
      thumbnail: "https://i.dummyjson.com/data/products/44/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 45,
      title: "Bose SoundLink Revolve+ Bluetooth Speaker",
      description:
        "A portable speaker with deep bass and 360-degree sound, perfect for indoor and outdoor use.",
      price: 299,
      discountPercentage: 8.5,
      rating: 4.7,
      stock: 65,
      brand: "Bose",
      category: "audio",
      thumbnail: "https://i.dummyjson.com/data/products/45/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 46,
      title: "Fitbit Charge 5 Fitness Tracker",
      description:
        "Track your fitness with the advanced Fitbit Charge 5 tracker with built-in GPS and heart rate monitoring.",
      price: 179,
      discountPercentage: 12.0,
      rating: 4.6,
      stock: 150,
      brand: "Fitbit",
      category: "fitness",
      thumbnail: "https://i.dummyjson.com/data/products/46/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 47,
      title: "Garmin Forerunner 245 Music GPS Running Watch",
      description:
        "Enhance your workouts with the Garmin Forerunner 245 Music GPS running watch with built-in music storage.",
      price: 299,
      discountPercentage: 10.5,
      rating: 4.7,
      stock: 70,
      brand: "Garmin",
      category: "fitness",
      thumbnail: "https://i.dummyjson.com/data/products/47/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 48,
      title: "Apple Watch Series 7 GPS, 41mm",
      description:
        "The Apple Watch Series 7 offers fitness tracking, health insights, and stunning display.",
      price: 399,
      discountPercentage: 9.0,
      rating: 4.8,
      stock: 100,
      brand: "Apple",
      category: "wearables",
      thumbnail: "https://i.dummyjson.com/data/products/48/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 49,
      title: "Samsung Galaxy Watch 4 Classic",
      description:
        "The Samsung Galaxy Watch 4 Classic is a premium smartwatch with fitness tracking and advanced health monitoring.",
      price: 249,
      discountPercentage: 11.2,
      rating: 4.6,
      stock: 80,
      brand: "Samsung",
      category: "wearables",
      thumbnail: "https://i.dummyjson.com/data/products/49/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 50,
      title: "Fitbit Sense Advanced Smartwatch",
      description:
        "Stay on top of your health and fitness with the Fitbit Sense smartwatch, featuring ECG and skin temperature sensors.",
      price: 299,
      discountPercentage: 8.0,
      rating: 4.7,
      stock: 120,
      brand: "Fitbit",
      category: "wearables",
      thumbnail: "https://i.dummyjson.com/data/products/50/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 51,
      title: "Sony PlayStation 5 Console",
      description:
        "The Sony PlayStation 5 is the next-generation gaming console with ultra-fast SSD, Ray Tracing, and an incredible selection of games.",
      price: 499,
      discountPercentage: 5.0,
      rating: 4.9,
      stock: 200,
      brand: "Sony",
      category: "gaming",
      thumbnail: "https://i.dummyjson.com/data/products/51/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 52,
      title: "Microsoft Xbox Series X",
      description:
        "Power your gaming experience with the Xbox Series X, the most powerful gaming console.",
      price: 499,
      discountPercentage: 6.0,
      rating: 4.8,
      stock: 150,
      brand: "Microsoft",
      category: "gaming",
      thumbnail: "https://i.dummyjson.com/data/products/52/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 53,
      title: "Nintendo Switch OLED Model",
      description:
        "Enjoy the immersive world of gaming with the Nintendo Switch OLED, offering vibrant visuals and portable gameplay.",
      price: 349,
      discountPercentage: 10.0,
      rating: 4.7,
      stock: 200,
      brand: "Nintendo",
      category: "gaming",
      thumbnail: "https://i.dummyjson.com/data/products/53/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 54,
      title: "Samsung 65-inch 4K UHD Smart TV",
      description:
        "Enjoy stunning visuals and an immersive entertainment experience with the Samsung 65-inch 4K UHD Smart TV.",
      price: 799,
      discountPercentage: 7.0,
      rating: 4.5,
      stock: 100,
      brand: "Samsung",
      category: "electronics",
      thumbnail: "https://i.dummyjson.com/data/products/54/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 55,
      title: "LG 55-inch OLED 4K TV",
      description:
        "An OLED masterpiece, the LG 55-inch 4K TV brings your favorite movies and shows to life with true-to-life color and clarity.",
      price: 1499,
      discountPercentage: 15.0,
      rating: 4.8,
      stock: 60,
      brand: "LG",
      category: "electronics",
      thumbnail: "https://i.dummyjson.com/data/products/55/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 56,
      title: "Apple MacBook Pro 13-inch M1 Chip",
      description:
        "The Apple MacBook Pro with M1 chip is the ultimate power machine with enhanced performance, ideal for professionals.",
      price: 1299,
      discountPercentage: 10.0,
      rating: 4.9,
      stock: 40,
      brand: "Apple",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/56/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 57,
      title: "Dell XPS 13 Laptop",
      description:
        "The Dell XPS 13 offers ultrathin design, amazing performance, and an ultra-responsive 13-inch display.",
      price: 999,
      discountPercentage: 5.0,
      rating: 4.7,
      stock: 80,
      brand: "Dell",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/57/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 58,
      title: "HP Spectre x360 Laptop",
      description:
        "The HP Spectre x360 is a sleek and versatile 2-in-1 laptop with incredible power and a high-resolution touchscreen display.",
      price: 1299,
      discountPercentage: 7.0,
      rating: 4.6,
      stock: 60,
      brand: "HP",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/58/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 59,
      title: "Lenovo ThinkPad X1 Carbon Gen 9",
      description:
        "Lenovo ThinkPad X1 Carbon is a powerful business laptop with a stunning 14-inch display and long battery life.",
      price: 1599,
      discountPercentage: 10.0,
      rating: 4.8,
      stock: 30,
      brand: "Lenovo",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/59/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 60,
      title: "Acer Predator Helios 300 Gaming Laptop",
      description:
        "The Acer Predator Helios 300 features a powerful i7 processor, an NVIDIA RTX 3060 GPU, and a 144Hz display for an immersive gaming experience.",
      price: 1299,
      discountPercentage: 12.0,
      rating: 4.6,
      stock: 90,
      brand: "Acer",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/60/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 61,
      title: "Bose QuietComfort 35 II Wireless Bluetooth Headphones",
      description:
        "The Bose QuietComfort 35 II headphones offer superior noise-canceling technology, incredible sound quality, and comfortable fit.",
      price: 299,
      discountPercentage: 10.0,
      rating: 4.7,
      stock: 150,
      brand: "Bose",
      category: "headphones",
      thumbnail: "https://i.dummyjson.com/data/products/61/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 62,
      title: "Sony WH-1000XM4 Noise Cancelling Wireless Headphones",
      description:
        "Enjoy exceptional sound quality and industry-leading noise cancellation with the Sony WH-1000XM4 headphones.",
      price: 349,
      discountPercentage: 8.0,
      rating: 4.9,
      stock: 200,
      brand: "Sony",
      category: "headphones",
      thumbnail: "https://i.dummyjson.com/data/products/62/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 63,
      title: "Beats Studio3 Wireless Noise Cancelling Over-Ear Headphones",
      description:
        "Beats Studio3 headphones deliver high-quality sound and superior noise cancellation for the best listening experience.",
      price: 379,
      discountPercentage: 12.0,
      rating: 4.8,
      stock: 120,
      brand: "Beats",
      category: "headphones",
      thumbnail: "https://i.dummyjson.com/data/products/63/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 64,
      title: "Apple AirPods Pro (2nd Generation)",
      description:
        "The Apple AirPods Pro delivers high-fidelity audio, adaptive transparency, and active noise cancellation in a small, portable design.",
      price: 249,
      discountPercentage: 5.0,
      rating: 4.9,
      stock: 300,
      brand: "Apple",
      category: "headphones",
      thumbnail: "https://i.dummyjson.com/data/products/64/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 65,
      title: "Samsung T7 Portable SSD 1TB",
      description:
        "The Samsung T7 Portable SSD offers fast transfer speeds with the convenience of compact portability, perfect for backup and storage needs.",
      price: 119,
      discountPercentage: 15.0,
      rating: 4.7,
      stock: 200,
      brand: "Samsung",
      category: "storage",
      thumbnail: "https://i.dummyjson.com/data/products/65/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 66,
      title: "SanDisk Ultra 1TB USB 3.0 Flash Drive",
      description:
        "The SanDisk Ultra 1TB USB Flash Drive offers fast data transfer with a compact and durable design for storing documents, photos, and videos.",
      price: 54,
      discountPercentage: 20.0,
      rating: 4.6,
      stock: 300,
      brand: "SanDisk",
      category: "storage",
      thumbnail: "https://i.dummyjson.com/data/products/66/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 67,
      title: "Western Digital 2TB My Passport Portable Hard Drive",
      description:
        "The WD My Passport 2TB portable hard drive is a high-capacity external storage solution with fast read/write speeds and sleek design.",
      price: 89,
      discountPercentage: 10.0,
      rating: 4.8,
      stock: 250,
      brand: "Western Digital",
      category: "storage",
      thumbnail: "https://i.dummyjson.com/data/products/67/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 68,
      title: "Seagate Expansion 4TB Portable External Hard Drive",
      description:
        "The Seagate Expansion 4TB portable external hard drive offers large storage capacity and fast data transfer for all your files and media.",
      price: 105,
      discountPercentage: 15.0,
      rating: 4.7,
      stock: 180,
      brand: "Seagate",
      category: "storage",
      thumbnail: "https://i.dummyjson.com/data/products/68/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 69,
      title: "Kingston A2000 1TB NVMe Internal SSD",
      description:
        "Boost your computer's performance with the Kingston A2000 1TB NVMe SSD, delivering ultra-fast read and write speeds for a smooth experience.",
      price: 69,
      discountPercentage: 12.0,
      rating: 4.6,
      stock: 160,
      brand: "Kingston",
      category: "storage",
      thumbnail: "https://i.dummyjson.com/data/products/69/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 70,
      title: "HyperX Alloy FPS Pro Mechanical Gaming Keyboard",
      description:
        "The HyperX Alloy FPS Pro is a compact mechanical keyboard designed for FPS gamers, featuring red LED backlighting and responsive keys.",
      price: 69,
      discountPercentage: 15.0,
      rating: 4.7,
      stock: 110,
      brand: "HyperX",
      category: "gaming",
      thumbnail: "https://i.dummyjson.com/data/products/70/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 71,
      title: "Razer DeathAdder V2 Wired Gaming Mouse",
      description:
        "The Razer DeathAdder V2 is a highly precise wired gaming mouse, designed for comfort and performance with optical mouse switches.",
      price: 49,
      discountPercentage: 10.0,
      rating: 4.8,
      stock: 150,
      brand: "Razer",
      category: "gaming",
      thumbnail: "https://i.dummyjson.com/data/products/71/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 72,
      title: "Logitech G Pro X Superlight Wireless Gaming Mouse",
      description:
        "The Logitech G Pro X Superlight is an ultra-lightweight wireless gaming mouse, built for professional-grade precision and performance.",
      price: 149,
      discountPercentage: 5.0,
      rating: 4.9,
      stock: 130,
      brand: "Logitech",
      category: "gaming",
      thumbnail: "https://i.dummyjson.com/data/products/72/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 73,
      title: "Corsair K70 RGB MK.2 Mechanical Gaming Keyboard",
      description:
        "The Corsair K70 RGB MK.2 is a premium mechanical gaming keyboard with Cherry MX key switches and customizable RGB backlighting.",
      price: 159,
      discountPercentage: 12.0,
      rating: 4.7,
      stock: 110,
      brand: "Corsair",
      category: "gaming",
      thumbnail: "https://i.dummyjson.com/data/products/73/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 74,
      title: "Acer Predator Helios 300 Gaming Laptop",
      description:
        "The Acer Predator Helios 300 features a 15.6-inch Full HD display, Intel i7 processor, and NVIDIA GTX 1660 Ti graphics, perfect for gaming.",
      price: 1299,
      discountPercentage: 10.0,
      rating: 4.6,
      stock: 70,
      brand: "Acer",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/74/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 75,
      title: "Asus ROG Zephyrus G14 Gaming Laptop",
      description:
        "The Asus ROG Zephyrus G14 offers incredible gaming performance with an AMD Ryzen 9 processor, NVIDIA GeForce RTX 3070, and a 14-inch display.",
      price: 1799,
      discountPercentage: 7.0,
      rating: 4.8,
      stock: 60,
      brand: "Asus",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/75/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 76,
      title: "Dell XPS 15 9500 Laptop",
      description:
        "The Dell XPS 15 is a powerful laptop with a 15.6-inch 4K OLED display, Intel Core i9 processor, and NVIDIA GTX 1650 Ti graphics.",
      price: 2399,
      discountPercentage: 15.0,
      rating: 4.9,
      stock: 45,
      brand: "Dell",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/76/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 77,
      title: "HP Spectre x360 13.3-Inch Laptop",
      description:
        "The HP Spectre x360 features a 13.3-inch touchscreen, Intel i7 processor, and 512GB SSD for all your productivity and creative needs.",
      price: 1499,
      discountPercentage: 10.0,
      rating: 4.7,
      stock: 80,
      brand: "HP",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/77/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 78,
      title: "Apple MacBook Air with M1 Chip",
      description:
        "The Apple MacBook Air with M1 chip is thin, lightweight, and packed with performance. Featuring 13.3-inch Retina display and long battery life.",
      price: 999,
      discountPercentage: 5.0,
      rating: 4.8,
      stock: 120,
      brand: "Apple",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/78/thumbnail.jpg",
      inCart: false,
      images: [],
    },
    {
      id: 79,
      title: "Microsoft Surface Laptop 4",
      description:
        "The Microsoft Surface Laptop 4 is sleek and powerful, with a 13.5-inch PixelSense display, Intel Core i7 processor, and long battery life.",
      price: 1299,
      discountPercentage: 8.0,
      rating: 4.7,
      stock: 150,
      brand: "Microsoft",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/79/thumbnail.jpg",
      inCart: false,
      images: [],
    },
  ],
  category: "all",
  minPrice: 0,
  maxPrice: 1000,
  sortOrder: "lowToHigh",
};
const setLocalStorage = (key, value) => {
  localStorage.setItem(key, JSON.stringify(value));
};

const getLocalStorage = (key, defaultValue) => {
  const storedValue = localStorage.getItem(key);
  return storedValue ? JSON.parse(storedValue) : defaultValue;
};
const init = () => {
  for (const key in initialState) {
    const temp = getLocalStorage(key);
    if (!temp) {
      setLocalStorage(key, initialState[key]);
    } else {
      initialState[key] = temp;
    }
  }
};
init();
export const ecartSlice = createSlice({
  name: "ecart",
  initialState,
  reducers: {
    add_cart: (state, action) => {
      const { id } = action.payload;
      const ifExist = state.cart.find((d) => d.id == id);
      const index = findIndex(state.products, id);

      const product = {
        ...state.products[index],
        quantity: 1,
      };
      const products = state.products.map((d) => {
        if (d.id == id) {
          return { ...d, inCart: false };
        }
        return d;
      });
      if (!ifExist) {
        toast.success("Item added successfully");
        setLocalStorage("cart", [...state.cart, product]);
        return { ...state, products, cart: [...state.cart, product] };
      }
      toast.info("Item already exist");
    },
    increase_cart: (state, action) => {
      const { id } = action.payload;
      const index = findIndex(state.cart, id);
      if (index !== -1) {
        state.cart[index] = {
          ...state.cart[index],
          quantity: (state.cart[index].quantity || 1) + 1,
        };
        init();
      }
    },
    decrease_cart: (state, action) => {
      const { id } = action.payload;
      const index = findIndex(state.cart, id);
      if (index !== -1 && state.cart[index].quantity > 1) {
        state.cart[index] = {
          ...state.cart[index],
          quantity: state.cart[index].quantity - 1,
        };
        init();
      }
    },
    remove_cart: (state, action) => {
      const { id } = action.payload;
      const products = state.products.map((d) => {
        if (d.id == id) {
          return { ...d, inCart: false };
        }
        return d;
      });
      toast.success("Item removed from cart");
      setLocalStorage(
        "cart",
        state.cart.filter((item) => item.id !== id)
      );
      return {
        ...state,
        products,
        cart: state.cart.filter((item) => item.id !== id),
      };
    },
    setCategory: (state, action) => {
      state.category = action.payload;
    },
    setPriceRange: (state, action) => {
      const { min, max } = action.payload;
      state.minPrice = min;
      state.maxPrice = max;
    },
    setSortOrders: (state, action) => {
      state.sortOrder = action.payload;
    },
    filterProducts: (state) => {
      let filtered = state.products.filter((product) => {
        return (
          product.price >= state.minPrice &&
          product.price <= state.maxPrice &&
          (state.category === "all" || product.category === state.category)
        );
      });
      if (state.sortOrder === "lowToHigh") {
        filtered.sort((a, b) => a.price - b.price);
      } else if (state.sortOrder === "highToLow") {
        filtered.sort((a, b) => b.price - a.price);
      }

      state.filteredProducts = filtered;
    },
  },
});

export const {
  setCategory,
  setPriceRange,
  setSortOrders,
  filterProducts,
  increase_cart,
  decrease_cart,
  remove_cart,
  add_cart,
} = ecartSlice.actions;
export const ecartReducer = ecartSlice.reducer;
export const selecteCart = (state) => state.ecart.cart;
export const selecteProduct = (state) => state.ecart.filteredProducts;
